var hierarchy =
[
    [ "AffineXf3f", "classAffineXf3f.html", null ],
    [ "BaseShellParameters", "classBaseShellParameters.html", [
      [ "OffsetParameters", "classOffsetParameters.html", [
        [ "SharpOffsetParameters", "classSharpOffsetParameters.html", [
          [ "GeneralOffsetParameters", "classGeneralOffsetParameters.html", null ]
        ] ]
      ] ]
    ] ],
    [ "BitSet", "classBitSet.html", [
      [ "EdgeBitSet", "classEdgeBitSet.html", null ],
      [ "FaceBitSet", "classFaceBitSet.html", null ],
      [ "UndirectedEdgeBitSet", "classUndirectedEdgeBitSet.html", null ],
      [ "VertBitSet", "classVertBitSet.html", null ]
    ] ],
    [ "BooleanResult", "classBooleanResult.html", null ],
    [ "BooleanResultMapper", "classBooleanResultMapper.html", null ],
    [ "Box3f", "classBox3f.html", null ],
    [ "Box3i", "classBox3i.html", null ],
    [ "Color", "classColor.html", null ],
    [ "CutByProjectionSettings", "classCutByProjectionSettings.html", null ],
    [ "CutMeshParameters", "classCutMeshParameters.html", null ],
    [ "DecimateResult", "classDecimateResult.html", null ],
    [ "DecimateSettings", "classDecimateSettings.html", null ],
    [ "DenoiseViaNormalsSettings", "classDenoiseViaNormalsSettings.html", null ],
    [ "DistanceFromWeightedPointsParams", "classDistanceFromWeightedPointsParams.html", null ],
    [ "Face2RegionMap", "classFace2RegionMap.html", null ],
    [ "FaceMap", "classFaceMap.html", null ],
    [ "FaceNormals", "classFaceNormals.html", null ],
    [ "FillHoleNicelySettings", "classFillHoleNicelySettings.html", null ],
    [ "FillHoleParams", "classFillHoleParams.html", null ],
    [ "FixMeshDegeneraciesParams", "classFixMeshDegeneraciesParams.html", null ],
    [ "FloatGrid", "classFloatGrid.html", null ],
    [ "FreeFormDeformer", "classFreeFormDeformer.html", null ],
    [ "GridToMeshSettings", "classGridToMeshSettings.html", null ],
    [ "ICP", "classICP.html", null ],
    [ "ICPProperties", "classICPProperties.html", null ],
    [ "Laplacian", "classLaplacian.html", null ],
    [ "Matrix3f", "classMatrix3f.html", null ],
    [ "Mesh", "classMesh.html", null ],
    [ "MeshBuilder", "classMeshBuilder.html", null ],
    [ "MeshComponents", "classMeshComponents.html", null ],
    [ "MeshLoad", "classMeshLoad.html", null ],
    [ "MeshOrPoints", "classMeshOrPoints.html", null ],
    [ "MeshOrPointsXf", "classMeshOrPointsXf.html", null ],
    [ "MeshProjectionParameters", "classMeshProjectionParameters.html", null ],
    [ "MeshRelaxParams", "classMeshRelaxParams.html", null ],
    [ "MeshSave", "classMeshSave.html", null ],
    [ "MeshTopology", "classMeshTopology.html", null ],
    [ "MeshToVolumeParams", "classMeshToVolumeParams.html", null ],
    [ "MultiwayICP", "classMultiwayICP.html", null ],
    [ "MultiwayICPSamplingParameters", "classMultiwayICPSamplingParameters.html", null ],
    [ "NoiseSettings", "classNoiseSettings.html", null ],
    [ "PointCloud", "classPointCloud.html", null ],
    [ "PointsLoad", "classPointsLoad.html", null ],
    [ "PointsSave", "classPointsSave.html", null ],
    [ "PointsToMeshParameters", "classPointsToMeshParameters.html", null ],
    [ "PreciseCollisionResult", "classPreciseCollisionResult.html", null ],
    [ "RemeshSettings", "classRemeshSettings.html", null ],
    [ "SelfIntersections", "classSelfIntersections.html", null ],
    [ "SelfIntersectionsSettings", "classSelfIntersectionsSettings.html", null ],
    [ "SmoothFillingSettings", "classSmoothFillingSettings.html", null ],
    [ "SphereParams", "classSphereParams.html", null ],
    [ "StitchHolesParams", "classStitchHolesParams.html", null ],
    [ "SubdivideFillingSettings", "classSubdivideFillingSettings.html", null ],
    [ "SubdivideSettings", "classSubdivideSettings.html", null ],
    [ "Triangulation", "classTriangulation.html", null ],
    [ "TriangulationParameters", "classTriangulationParameters.html", null ],
    [ "UniformSamplingSettings", "classUniformSamplingSettings.html", null ],
    [ "VarEdgeTri", "classVarEdgeTri.html", null ],
    [ "VdbVolume", "classVdbVolume.html", null ],
    [ "Vector3", "classVector3.html", null ],
    [ "Vector3f", "classVector3f.html", null ],
    [ "Vector3i", "classVector3i.html", null ],
    [ "VertColors", "classVertColors.html", null ],
    [ "VertCoords", "classVertCoords.html", null ],
    [ "VertMap", "classVertMap.html", null ],
    [ "VertScalars", "classVertScalars.html", null ],
    [ "VoxelsLoad", "classVoxelsLoad.html", null ],
    [ "VoxelsSave", "classVoxelsSave.html", null ],
    [ "WeightedShell", "classWeightedShell.html", null ],
    [ "WeightedShellParametersBase", "classWeightedShellParametersBase.html", [
      [ "WeightedShellParametersMetric", "classWeightedShellParametersMetric.html", null ]
    ] ]
];