var group__IOGroup =
[
    [ "Base64", "group__Base64Group.html", "group__Base64Group" ],
    [ "DistanceMap Load", "group__DistanceMapLoadGroup.html", "group__DistanceMapLoadGroup" ],
    [ "DistanceMap Save", "group__DistanceMapSaveGroup.html", "group__DistanceMapSaveGroup" ],
    [ "Gcode Load", "group__GcodeLoadGroup.html", "group__GcodeLoadGroup" ],
    [ "Image Load", "group__ImageLoadGroup.html", "group__ImageLoadGroup" ],
    [ "Image Save", "group__ImageSaveGroup.html", "group__ImageSaveGroup" ],
    [ "IO Filters", "group__IOFiltersGroup.html", "group__IOFiltersGroup" ],
    [ "IO Formats Registry", "group__IOFormatsRegistryGroup.html", "group__IOFormatsRegistryGroup" ],
    [ "Lines Load", "group__LinesLoad.html", "group__LinesLoad" ],
    [ "Lines Save", "group__LinesSaveGroup.html", "group__LinesSaveGroup" ],
    [ "Mesh Load", "group__MeshLoadGroup.html", "group__MeshLoadGroup" ],
    [ "Mesh Load Obj", "group__MeshLoadObjGroup.html", "group__MeshLoadObjGroup" ],
    [ "Mesh Save", "group__MeshSaveGroup.html", "group__MeshSaveGroup" ],
    [ "Mesh Save Obj", "group__MeshSaveObjGroup.html", "group__MeshSaveObjGroup" ],
    [ "Points Save", "group__PointsSaveGroup.html", "group__PointsSaveGroup" ],
    [ "Serializer", "group__SerializerGroup.html", "group__SerializerGroup" ],
    [ "Voxels Load", "group__VoxelsLoadGroup.html", "group__VoxelsLoadGroup" ],
    [ "Voxels Save", "group__VoxelsSaveGroup.html", "group__VoxelsSaveGroup" ],
    [ "MR::PointsLoad::fromAnySupportedFormat", "group__IOGroup.html#ga7ffd96e7cc233f9a5d99dfc3e8bb0edb", null ],
    [ "MR::PointsLoad::fromAnySupportedFormat", "group__IOGroup.html#gaecd3b7671e06c949d93c808ec95506f7", null ],
    [ "MR::PointsLoad::fromDxf", "group__IOGroup.html#ga0bcd39338d08939438531f7d5c9d077d", null ],
    [ "MR::PointsLoad::fromDxf", "group__IOGroup.html#ga72bf2e744527a6f283dc17ddb3f49317", null ],
    [ "MR::PointsLoad::fromObj", "group__IOGroup.html#ga6b969b26544c7ea1a5d6c27d3f6dce43", null ],
    [ "MR::PointsLoad::fromObj", "group__IOGroup.html#ga80e4f60af0a019706ae5488aa2d1acb2", null ],
    [ "MR::PointsLoad::fromPly", "group__IOGroup.html#ga352bcd3eb201034b3436586ca04f097b", null ],
    [ "MR::PointsLoad::fromPly", "group__IOGroup.html#ga63584572783b16916778f68be00de68b", null ],
    [ "MR::PointsLoad::fromPts", "group__IOGroup.html#ga182f784fd22c46cd583b17466226b26a", null ],
    [ "MR::PointsLoad::fromPts", "group__IOGroup.html#ga756bfbe6cede3121408e2ef95f428411", null ],
    [ "MR::PointsLoad::fromText", "group__IOGroup.html#ga1c3cebd38d164d456af80671f7250fbf", null ],
    [ "MR::PointsLoad::fromText", "group__IOGroup.html#gacc3b6b39e72f9a09af6653f353e66998", null ],
    [ "MR::PointsLoad::telemetryLogSize", "group__IOGroup.html#ga56f3c968fa0da7592fff9bf39304344e", null ]
];